version: '2'
services:
  api:
    restart: always
    image: autotrade/autotrade
    volumes:
      - ./autotrade/conf.json:/mnt/autotrade/conf.json
    env_file: ./envrc
    command: bash -c "python /mnt/autotrade/bin/app.py"
    ports:
      - 8000:8080
  worker:
    restart: always
    image: autotrade/autotrade
    volumes:
      - .:/mnt
    links:
      - mysql
    env_file: ./envrc
    command: bash -c "while true; do python /mnt/autotrade/bin/worker.py; sleep 60; done;"
  chart:
    restart: always
    links:
      - mysql
    image: autotrade/autotrade
    command: bash -c "while true; do python /mnt/autotrade/bin/make_chart.py; done;"
  metabase:
    restart: always
    image: metabase/metabase
    env_file: ./envrc
    links:
      - mysql
    volumes:
      - ./val/metabase:/metabase-data
    ports:
     - 3000:3000
  mysql:
    restart: always
    image: mysql
    env_file: ./envrc
    volumes:
     - ./db:/var/lib/mysql
  grafana:
    restart: always
    image: grafana/grafana
    env_file: ./envrc
    links:
      - mysql
    volumes:
      - ./val/grafana:/var/lib/grafana
    ports:
      - 3001:3000
